config/routes.rb
Rails.application.routes.draw do
  # get 'customer/index'

  resources :customers

  root 'customers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	validates :name, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
=begin
A frequent practice is to place the standard CRUD actions in each controller 
in the following order: index, show, new, edit, create, update and destroy. 
You may use any order you choose, but keep in mind that these are public methods; 
and they must be placed before any private or protected method in the 
controller in order to work.	
=end
	def test()
		# /customer/test/?phone_number=072888888&email=dhh@email.com
		render plain: params[:phone_number].inspect
	end
	# GET
	def index
	    @customers = Customer.all
	end

	# GET
	def edit
		@customer = Customer.find(params[:id])
	end

	# GET
	def show()
		# get the :id parameter from the request
		# We use an instance variable (prefixed with @) to hold a reference 
		# to the customer object. We do this because Rails will pass all 
		# instance variables to the view.
    	@customer = Customer.find(params[:id])
  	end

	# GET
	def new
		@customer = Customer.new
	end
 
	# POST
	def create
		# render plain: params[:customer].inspect
		# name"=>"", "phone_number"=>""
		# render plain: params[:phone_number].inspect
		# @customer = Customer.new(params[:customer])

		# whitelist our controller parameters to prevent wrongful mass assignment. 
		# @customer = Customer.new(params.require(:customer).permit(:name, :phone_number))

		@customer = Customer.new(customer_params)

		# save is responsible for saving the model in the database
		# @customer.save returns a boolean indicating whether the customer was saved or not.
		# @customer.save
		# redirect the user to the show action
		# redirect_to @customer
		if @customer.save
			# redirect_to tells the browser to issue another request.
		    redirect_to @customer
		else
			# The render method is used so that the @customer object 
			# is passed back to the new template when it is rendered. 
			# This rendering is done within the same request as the form submission
		    render 'new'
		end
	end



	# PUT/PATCH
	def update
		@customer = Customer.find(params[:id])
 
 		# @customer.update(name: 'Updated name')
		if @customer.update(customer_params)
			redirect_to @customer
		else
			render 'edit'
		end
	end

	# DELETE
	
	def destroy
	  	@customer = Customer.find(params[:id])
	  	@customer.destroy
	 
	  	redirect_to customers_path
	end
	# private to make sure it can't be called outside its intended context.
	private
	  def customer_params
	    params.require(:customer).permit(:name, :phone_number)
	  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
 
  <% if @customer.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> prohibited
        this customer from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control', placeholder: "Enter your name" %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number, :class => 'form-control', placeholder: "Enter your phone" %>
  </div>
 
  <p>
    <%= f.submit :class => 'btn btn-success' %>
  </p>
 
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>
 
<%= render 'form' %>
 
<%= link_to '<<Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<button type="button" class="btn btn-primary btn-lg"><%= link_to 'New customer', new_customer_path %></button>
<table class="table">
  <thead class="thead-light">
  <tr>
    <th>Name</th>
    <th>Phone</th>
  </tr>
</thead>
  <tbody> 
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.phone_number %></td>
      <td> <%= link_to 'Show', customer_path(customer) %> </td>
      <td> <%= link_to 'Edit', edit_customer_path(customer) %> </td>
      <td> <%= link_to 'Destroy', customer_path(customer),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/customers/new.html.erb
<h1>New customer</h1>
 
<%= render 'form' %>
 
<%= link_to '<<Back', customers_path %>

app/views/customers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>
 
<p>
  <strong>Phone No:</strong>
  <%= @customer.phone_number %>
</p>
<%= link_to 'Edit', edit_customer_path(@customer) %> | <%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EGRANARY</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>